In [2]:
!pip install picos

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.7/510.7 kB 2.3 MB/s eta 0:00:000:00:01m eta 0:00:01
  Preparing metadata (setup.py) ... done
  Created wheel for picos: filename=PICOS-2.4.17-py3-none-any.whl size=472079 sha256=5e683926e263bd8dd9c0e8be3e9a07f6974ccf6fee05af5fd1e8922e0568a4b8
  Stored in directory: /Users/laengle-uchile/Library/Caches/pip/wheels/11/3f/e8/e37a87c4461222bbd83cd40c3d6c01ffa34c36a5f39f1c1951
Successfully built picos


In [5]:
import picos as pic
import cvxopt as cvx

In [9]:
n=3
m=4
M = cvx.normal(n,m) #generate a random matrix
print(M)

[-1.67e-01  8.51e-01  2.17e-02 -1.31e+00]
[ 9.13e-01 -8.14e-01 -7.38e-01  6.00e-01]
[ 2.10e+00  5.59e-02  6.19e-01  8.60e-01]



In [26]:
from picos import Problem, RealVariable

In [30]:
z = RealVariable("z", 3)

TypeError: Shapes must be given as None, int, tuple or list.

In [22]:
from picos import Problem
P = Problem()
x = P.add_variable('x', 3)
x

In [31]:
import numpy as np
import picos as pc
from matplotlib import pyplot
from scipy import spatial

In [32]:
# Make the result reproducible.
np.random.seed(12)

# Define the data.
n = 20
A = np.random.rand(2, n)
b = np.array([1, 0])

In [40]:
x = pc.RealVariable("x", shape = (1, n))

In [43]:
# Define and solve the problem.
P = pc.Problem()
P.minimize = abs(A*x - b)

TypeError: Invalid operation BiaffineExpression.__rmul__(x, array([[0.15416284, 0.7400497 , 0.26331502, 0.53373939, 0.01457496,
        0.91874701, 0.90071485, 0.03342143, 0.95694934, 0.13720932,
        0.28382835, 0.60608318, 0.94422514, 0.85273554, 0.00225923,
        0.52122603, 0.55203763, 0.48537741, 0.76813415, 0.16071675],
       [0.76456045, 0.0208098 , 0.13521018, 0.11627302, 0.30989758,
        0.67145265, 0.47122978, 0.8161683 , 0.28958678, 0.73312598,
        0.70262236, 0.32756948, 0.33464753, 0.97805808, 0.62458211,
        0.95031352, 0.76747565, 0.82500925, 0.4066403 , 0.45130841]])): Could not load right hand side as a constant of matching shape.